### ISSUE TITLE
Philips PM5655 VITS generator

### ISSUE THREAD

**Issue by goscickiw** [inaxeon/PTV_Preservation#1]
Hello,
I have recently bought an old used Philips PM5655 VIT signal and substitution test pattern generator. It didn't come with a manual or any technical documentation (other than a single page that was taped to it), and also I wasn't able to find any online, so I had to figure out how to use it on my own. It works well, but there's still some features whose purpose I'm not sure about, for example the "FULL FIELD" button.

I found this repository that seems to have information about similar devices, but still not this one. Would you be able to find more about it? Can I do anything else to help find more information? Maybe I could try to get the ROMs but I'm not sure yet if I have the correct tools, and I would rather not break it.

Here are some pictures of the device:
![IMG_20231028_111748](https://github.com/inaxeon/PTV_Preservation/assets/39399945/e8d76f0a-ae1e-4520-a7e1-df03af0120b5)
![IMG_20231028_111800](https://github.com/inaxeon/PTV_Preservation/assets/39399945/a70fa33b-0cf1-4512-b115-44391960d515)
![IMG_20231028_111808](https://github.com/inaxeon/PTV_Preservation/assets/39399945/b966c3e4-f354-4ca6-934f-5ff8f765b532)
![IMG_20231028_111818](https://github.com/inaxeon/PTV_Preservation/assets/39399945/28317c87-4c71-46aa-ba39-d70629674186)
![IMG_20231028_111827](https://github.com/inaxeon/PTV_Preservation/assets/39399945/97187ee6-b539-4d6e-8a25-5d062248928c)
![IMG_20231028_111833](https://github.com/inaxeon/PTV_Preservation/assets/39399945/8b2327a7-2bd3-4de6-b3fd-f2e01b76a3ba)
![IMG_20231028_112244](https://github.com/inaxeon/PTV_Preservation/assets/39399945/4419aaac-10d1-4e24-b807-edc312a4e4ee)
![IMG_20231028_112257](https://github.com/inaxeon/PTV_Preservation/assets/39399945/17f08b62-ec1b-4faa-b3fd-a1ee4abb183a)
![IMG_20231028_112311](https://github.com/inaxeon/PTV_Preservation/assets/39399945/61ad009b-3370-40ba-8c2d-f0a5df2e66c8)
![IMG_20231028_112358](https://github.com/inaxeon/PTV_Preservation/assets/39399945/ffd8cfdd-30fd-430c-9cb7-35a6bf58aa2c)
![IMG_20231028_112416](https://github.com/inaxeon/PTV_Preservation/assets/39399945/469e8e2d-a827-4806-9f29-55d49d6698b0)
![img20231028_11550290_1](https://github.com/inaxeon/PTV_Preservation/assets/39399945/dafa802d-cac8-4cbe-8ee0-47dd0b5a729e)
![test](https://github.com/inaxeon/PTV_Preservation/assets/39399945/bc969c65-fe27-4b86-aa0d-942cb8367628)

**Comment by inaxeon** [comment]
Unfortunately I cannot help with any documentation for it. Manuals for these products are basically unobtainable unless you got it with the unit. Today the products belong to Trescal but I have never managed to get a helpful response from them.

DK-Technologies released PTV schematics in CADSTAR for DOS format (https://github.com/KarstenHervoeHansen/PTV/tree/main/Cadstar%20jobs_arkiv%20fra%20PTV/Pcb_scm.std) and I have converted some of them to PDF here. Perhaps the PM5655 is also in there but this is not much help to you likely. They do not have anything else and it is presently unknown if any surviving this documentation exists.

Perhaps drop me an email: inaxeon@hotmail.com I would like to hear anything you learn about it.
